### ISSUE TITLE
Pipeline performance as described by medicare data coverage

### ISSUE THREAD

**Issue by jckitch** [NSAPH-Data-Processing/zip2county_master_xwalk#23]

**Comment by audiracmichelle** [comment]
here is the information of the data that you will need for this analysis: 

- **path** /n/dominici_nsaph_l3/Lab/parquet_dw/dorieh/medicare_schema
- **files** enroll_yyyy.parquet

columns:
            bene_id,
            year,
            state,
            zip,
            curec,
            hmo,
            hmo_indicators,
            hmo_cvg_count,
            buyin_indicators,
            dual_indicators,
            buyin_cvg_count,
            dual_cvg_count,
            buyin,
            dual

**Comment by audiracmichelle** [comment]
@jckitch since the data is stored in parquet, then reading should be pretty fast (whereas csv would be extremely slow). But let me know if that is not the case.

You can read parquet in R using the pyarrow package. There is also duckdb for R. Using duckdb you can query directly the columns that you need from all the files without the need to loop a read_parquet function. That is 
"SELECT zip FROM 'enroll_*.parquet'"

**Comment by audiracmichelle** [comment]
The notebook was incorporated in a private repo as it uses medicare data https://github.com/NSAPH-Data-Processing/mbsf_mortality_denom/blob/main/notes/medicare_xwalk_stats.ipynb
